package io.klimiter.core.api

import io.klimiter.core.api.spi.CompositeKeyGenerator
import io.klimiter.core.api.spi.KeyGenerator
import io.klimiter.core.api.spi.RateLimitDomainRepository
import io.klimiter.core.api.spi.RateLimitOperationFactory
import io.klimiter.core.api.spi.SystemTimeProvider
import io.klimiter.core.internal.DefaultKLimiter
import io.klimiter.core.internal.infra.store.InMemoryRateLimitStore
import io.klimiter.core.internal.operation.DefaultRateLimitOperationFactory
import org.slf4j.LoggerFactory
import kotlin.time.Duration

class KLimiterBuilder {
    private var domainRepository: RateLimitDomainRepository? = null
    private var maxCacheSize: Long? = null
    private var gracePeriod: Duration = InMemoryRateLimitStore.DEFAULT_GRACE_PERIOD
    private var keyGenerator: KeyGenerator = CompositeKeyGenerator
    private var customFactory: RateLimitOperationFactory? = null

    /**
     * Provides the source of rate-limit domain configurations. Called on every
     * [KLimiter.shouldRateLimit] invocation — the repository is responsible for any caching
     * needed to keep the hot path fast.
     *
     * Use [io.klimiter.core.api.spi.StaticRateLimitDomainRepository] for fixed configurations
     * known at startup; implement [RateLimitDomainRepository] directly for file-based,
     * database-backed, or hot-reloadable configurations.
     *
     * Must not be used together with [operationFactory].
     */
    fun domainRepository(repository: RateLimitDomainRepository): KLimiterBuilder = apply {
        domainRepository = repository
    }

    /**
     * Bounds the internal cache of rate-limit buckets. When unset the cache is unbounded,
     * which exposes the service to memory pressure if arbitrary keys can be generated by
     * callers (e.g., adversarial user_id values). Under the limit the cache evicts least-
     * recently-used entries.
     *
     * Only applies to the default in-memory backend; must not be used with [operationFactory].
     */
    fun maxCacheSize(size: Long): KLimiterBuilder = apply {
        require(size > 0) { "maxCacheSize must be > 0" }
        maxCacheSize = size
    }

    /**
     * Extra time each bucket stays in the cache beyond its logical window TTL, to absorb
     * GC pauses / scheduler delays between the clock read and the cache lookup. Too small
     * a value re-opens the "concurrent-window leak" (Caffeine recreates the same bucket
     * mid-window, doubling the limit); too large wastes memory proportionally to the number
     * of active users. Default (30s) covers realistic worst cases short of pathological
     * swap/full-GC. Increase on constrained hosts (tight Kubernetes CPU limits, swap enabled,
     * very large heaps); decrease only if memory is tight and the runtime is well-tuned.
     *
     * Only applies to the default in-memory backend; must not be used with [operationFactory].
     */
    fun gracePeriod(duration: Duration): KLimiterBuilder = apply {
        require(!duration.isNegative()) { "gracePeriod must not be negative" }
        gracePeriod = duration
    }

    /**
     * Overrides the key generator used to derive bucket cache keys. Only applies to the
     * default in-memory backend; must not be used with [operationFactory].
     *
     * Default: [io.klimiter.core.api.spi.CompositeKeyGenerator].
     */
    fun keyGenerator(generator: KeyGenerator): KLimiterBuilder = apply {
        keyGenerator = generator
    }

    /**
     * Replaces the default in-memory factory with a custom backend (e.g. Redis). The factory
     * must be thread-safe and is responsible for its own domain matching.
     *
     * Must not be combined with [domainRepository], [maxCacheSize], [gracePeriod], or [keyGenerator].
     */
    fun operationFactory(factory: RateLimitOperationFactory): KLimiterBuilder = apply {
        customFactory = factory
    }

    fun build(): KLimiter {
        val custom = customFactory
        if (custom != null) {
            check(domainRepository == null) {
                "domainRepository must not be used with operationFactory — the custom factory owns domain matching"
            }
            check(maxCacheSize == null) {
                "maxCacheSize applies to the default in-memory backend only"
            }
            check(gracePeriod == InMemoryRateLimitStore.DEFAULT_GRACE_PERIOD) {
                "gracePeriod applies to the default in-memory backend only"
            }
            check(keyGenerator === CompositeKeyGenerator) {
                "keyGenerator applies to the default in-memory backend only"
            }
            logger.info("KLimiter built backend={}", custom::class.simpleName)
            return DefaultKLimiter(custom)
        }
        val repo = checkNotNull(domainRepository) { "domainRepository must be configured" }
        val store = InMemoryRateLimitStore(
            maxCacheSize = maxCacheSize,
            gracePeriod = gracePeriod,
        )
        val factory = DefaultRateLimitOperationFactory(
            domainRepository = repo,
            store = store,
            keyGenerator = keyGenerator,
            timeProvider = SystemTimeProvider,
        )
        logger.info(
            "KLimiter built backend=in-memory maxCacheSize={} gracePeriod={}",
            maxCacheSize ?: "unbounded",
            gracePeriod,
        )
        return DefaultKLimiter(factory)
    }

    companion object {
        private val logger = LoggerFactory.getLogger(KLimiterBuilder::class.java)
        fun create(): KLimiterBuilder = KLimiterBuilder()
    }
}
