package io.klimiter.core.api

import io.klimiter.core.api.config.RateLimitDomain
import io.klimiter.core.internal.DefaultKLimiterBuilder
import kotlin.time.Duration

interface KLimiterBuilder {
    fun addDomain(domain: RateLimitDomain): KLimiterBuilder
    fun addDomains(domains: Collection<RateLimitDomain>): KLimiterBuilder

    /**
     * Bounds the internal cache of rate-limit buckets. When unset the cache is unbounded,
     * which exposes the service to memory pressure if arbitrary keys can be generated by
     * callers (e.g., adversarial user_id values). Under the limit the cache evicts least-
     * recently-used entries.
     */
    fun maxCacheSize(size: Long): KLimiterBuilder

    /**
     * Extra time each bucket stays in the cache beyond its logical window TTL, to absorb
     * GC pauses / scheduler delays between the clock read and the cache lookup. Too small
     * a value re-opens the "concurrent-window leak" (Caffeine recreates the same bucket
     * mid-window, doubling the limit); too large wastes memory proportionally to the number
     * of active users. Default (30s) covers realistic worst cases short of pathological
     * swap/full-GC. Increase on constrained hosts (tight Kubernetes CPU limits, swap enabled,
     * very large heaps); decrease only if memory is tight and the runtime is well-tuned.
     */
    fun gracePeriod(duration: Duration): KLimiterBuilder

    fun build(): KLimiter

    companion object {
        fun create(): KLimiterBuilder = DefaultKLimiterBuilder()
    }
}
