spring:
  application:
    name: ${SPRING_APPLICATION_NAME:klimiter-service}
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:./config/klimiter-domains.yaml
      - optional:classpath:klimiter-domains.yaml
  grpc:
    server:
      port: ${GRPC_PORT:9090}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics,env,configprops}
  endpoint:
    health:
      probes:
        enabled: ${MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED:true}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0}
  otlp:
    metrics:
      export:
        enabled: ${OTLP_METRICS_EXPORT_ENABLED:false}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
    logging:
      export:
        otlp:
          endpoint: ${OTLP_LOGGING_ENDPOINT:http://localhost:4318/v1/logs}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

klimiter:
  backend:
    mode: ${KLIMITER_BACKEND_MODE:IN_MEMORY} # IN_MEMORY, REDIS_STANDALONE, REDIS_CLUSTER
    redis:
      uri: ${KLIMITER_BACKEND_REDIS_URI:redis://localhost:6379}
      uris: ${KLIMITER_BACKEND_REDIS_URIS:redis://localhost:7001,redis://localhost:7002,redis://localhost:7003}
      lease-percentage: ${KLIMITER_BACKEND_REDIS_LEASE_PERCENTAGE:10}
      key-prefix: ${KLIMITER_BACKEND_REDIS_KEY_PREFIX:klimiter}
