spring:
  application:
    name: klimiter-service
  grpc:
    server:
      port: 9090
  docker:
    compose:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 0
  otlp:
    metrics:
      export:
        enabled: false
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
logging:
  level:
    root: INFO

klimiter:
  domain-id: ${KLIMITER_DOMAIN_ID:default}
  key: ${KLIMITER_KEY:user_id}
  mode: ${KLIMITER_MODE:local}  # local | standalone | cluster
  default:
    limit: ${KLIMITER_DEFAULT_LIMIT:60}
    unit: ${KLIMITER_DEFAULT_UNIT:SECOND}
  redis:
    uris: ${KLIMITER_REDIS_URIS:redis://localhost:6379}
    lease-percentage: ${KLIMITER_REDIS_LEASE_PERCENTAGE:10}
    key-prefix: ${KLIMITER_REDIS_KEY_PREFIX:klimiter}
